site_name: Ballerina.io
repo_url: https://github.com/ballerina-platform/ballerina-www/blob/master/
edit_uri: website/two-column-pages/docs/
site_description: Documentation for the Ballerina Programming Language
site_author: WSO2, Inc.
copyright: 2018 WSO2, Inc.
pages:
- Learn: 'learn.md'
- Learn:
    - Quick Tour: 'learn/quick-tour.md'
    - Getting Started: 'learn/getting-started.md'
    - Tools, IDEs, and the Ballerina Composer: 'learn/tools-ides-ballerina-composer.md'
    - How to write secure ballerina code: 'learn/how-to-write-secure-ballerina-code.md'
    - How to observe ballerina code: 'learn/how-to-observe-ballerina-code.md'
    - How to structure ballerina code: 'learn/how-to-structure-ballerina-code.md'
    - How to extend ballerina: 'learn/how-to-extend-ballerina.md'
    - How to deploy and run ballerina programs: 'learn/how-to-deploy-and-run-ballerina-programs.md'
    - How to test ballerina code: 'learn/how-to-test-ballerina-code.md'
    - How to document ballerina code: 'learn/how-to-document-ballerina-code.md'
    - How to Publish Packages: 'learn/how-to-publish-packages.md'
    - FAQ: 'learn/faq.md'
    - Ballerina streaming reference: 'learn/ballerina-streaming-reference.md'
    - Events: 'learn/events.md'
    - Events:
        - Past Events: 'learn/events/past-events.md'
        - Ballerina Day Colombo 2018: 'learn/events/ballerina-day-colombo-2018.md'
        - Ballerina Day Colombo 2018:
            - Ballerina Day Colombo 2018 Confirmation: 'learn/events/ballerina-day-colombo-2018/ballerina-day-colombo-2018-confirmation.md'
        - Webinars: 'learn/events/webinars.md'
        - Webinars:
            - Ballerina Serverless with Kubeless: 'learn/events/webinars/ballerina-serverless-with-kubeless.md'
            - Container Native Log Processing with Ballerina + Humio: 'learn/events/webinars/container-native-log-processing-with-ballerina-and-humio.md'
            - Continuous Delivery for Cloud Native Applications with Kubernetes, Ballerina, and Codefresh: 'learn/events/webinars/continuous-delivery-for-cloud-native-applications-with-kubernetes-ballerina-and-codefresh.md'
        - Ballerinacon San Francisco 2018:
            - Ballerina Serverless with Kubeless: 'learn/events/ballerinacon-san-francisco-2018/ballerina-cloud-native-programming-language.md'
            - Ballerina is not Java (or Go or ..): 'learn/events/ballerinacon-san-francisco-2018/ballerina-is-not-java-or-go-or.md'
            - Microservice Integration & Ballerina: 'learn/events/ballerinacon-san-francisco-2018/microservice-Integration-and-ballerina.md'
            - Service Resiliency in Microservices: 'learn/events/ballerinacon-san-francisco-2018/service-resiliency-in-microservices.md'
            - Cloud Native Programing with Docker and Kubernetes: 'learn/events/ballerinacon-san-francisco-2018/cloud-native-programing-with-docker-and-kubernetes.md'
            - Service Mesh in Practice: 'learn/events/ballerinacon-san-francisco-2018/service-mesh-in-practice.md'
            - Test Driven Development for Microservices: 'learn/events/ballerinacon-san-francisco-2018/test-driven-development-for-microservices.md'
            - Serverless Ballerina: 'learn/events/ballerinacon-san-francisco-2018/serverless-ballerina.md'
            - Observability with Ballerina: 'learn/events/ballerinacon-san-francisco-2018/observability-with-ballerina.md'
            - Ballerina Development Lifecycle and Tools: 'learn/events/ballerinacon-san-francisco-2018/ballerina-development-lifecycle-and-tools.md'
            - Secure by Design Microservices & Integrations: 'learn/events/ballerinacon-san-francisco-2018/secure-by-design-microservices-and-integrations.md'
            - Stream Processing with Ballerina: 'learn/events/ballerinacon-san-francisco-2018/stream-processing-with-ballerina.md'
- Open Source : 'open-source.md'
- Open Source :
    - Slack : 'open-source/slack.md'
- Help : 'help.md'
- License of site : 'license-of-site.md'
- Terms of Service : 'terms-of-service.md'
- Privacy Policy : 'privacy-policy.md'
- Security : 'security.md'
- Downloads :
     - Release Notes : 'downloads/release-notes.md'
- Community Program : 'community-program.md'

theme: null
theme_dir: ballerina.io-two-col-theme
plugins: []
extra :
    base_download_url : 'https://product-dist.ballerina.io/downloads'
    archived_versions_json : 'https://product-dist.ballerina.io/downloads/archived_releases.json'
    archived_release_note_html : 'RELEASE_NOTE.html'
    nightly_versions_json : 'https://product-dist.ballerina.io/downloads/nightly_release.json'
    latest_versions_json : 'https://product-dist.ballerina.io/downloads/latest_release.json'
